import { getViewportHeight, getContentScaleRatio } from './canvas-ratio'

export enum CONTEXT {
  SIDE,
  DIALOG
}

export enum TYPOGRAPHY_TOKENS {
  TITLE_XL,
  TITLE_L,
  TITLE_M,
  POPUP_TITLE,
  BODY,
  BODY_S,
  LABEL,
  TAG,
  CAPTION,
  CAPTION_S_BOTTOM,
  MONO,
  BUTTON_ICON,
  BUTTON_ICON_BORDER_RADIUS,
  NAV_BUTTON,
  NAV_BUTTON_PADDING,
  NAV_BUTTON_HEIGHT,
  NAV_BUTTON_MARGIN
}

const TYPO_SCALE: Record<TYPOGRAPHY_TOKENS, number> = {
  [TYPOGRAPHY_TOKENS.TITLE_XL]: 2.4,
  [TYPOGRAPHY_TOKENS.TITLE_L]: 1.9,
  [TYPOGRAPHY_TOKENS.TITLE_M]: 1.4,
  [TYPOGRAPHY_TOKENS.POPUP_TITLE]: 1.4,
  [TYPOGRAPHY_TOKENS.BODY]: 1.2,
  [TYPOGRAPHY_TOKENS.BODY_S]: 0.9,
  [TYPOGRAPHY_TOKENS.LABEL]: 0.85,
  [TYPOGRAPHY_TOKENS.TAG]: 0.8,
  [TYPOGRAPHY_TOKENS.CAPTION]: 0.75,
  [TYPOGRAPHY_TOKENS.CAPTION_S_BOTTOM]: 0.3,
  [TYPOGRAPHY_TOKENS.MONO]: 0.95,
  [TYPOGRAPHY_TOKENS.BUTTON_ICON]: 1.8,
  [TYPOGRAPHY_TOKENS.BUTTON_ICON_BORDER_RADIUS]: 0.6,
  [TYPOGRAPHY_TOKENS.NAV_BUTTON]: 1.2,
  [TYPOGRAPHY_TOKENS.NAV_BUTTON_PADDING]: 1.2 * 0.5,
  [TYPOGRAPHY_TOKENS.NAV_BUTTON_HEIGHT]: 1.2 * 2.5,
  [TYPOGRAPHY_TOKENS.NAV_BUTTON_MARGIN]: 1.2 * 0.5
}

const BASE_FONT_SIZE = 14

export function getFontSize({
  context = CONTEXT.SIDE,
  token = TYPOGRAPHY_TOKENS.BODY
}): number {
  const scale = TYPO_SCALE[token]
  if (context === CONTEXT.DIALOG) {
    return BASE_FONT_SIZE * scale * getContentScaleRatio() * 2.06
  }
  return getViewportHeight() * 0.015 * scale
}
